"""empty message

Revision ID: 238b4ca6541f
Revises: 07d19a9a3384
Create Date: 2018-11-09 23:26:21.248467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238b4ca6541f'
down_revision = '07d19a9a3384'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('dislikes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'dislikes')
    # ### end Alembic commands ###
