"""Added additional fields to user model

Revision ID: 95c12ca9a11f
Revises: 511c08657d09
Create Date: 2018-10-31 17:04:11.337454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c12ca9a11f'
down_revision = '511c08657d09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone_number')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'date_of_birth')
    # ### end Alembic commands ###
